name: pattern_input_formatter
description: "Flutter PatternInputFormatter. Supports custom patterns (e.g., '(###) ###-####'), placeholders, and manages cursor position."
version: 0.1.0
homepage: "https://github.com/paooxide/pattern_input_formatter"
repository: https://github.com/paooxide/pattern_input_formatter
issue_tracker: https://github.com/paooxide/pattern_input_formatter/issues
topics:
  - flutter
  - date
  - input
  - formatter
  - text-input

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
